### ISSUE TITLE
prevent multiclick

### ISSUE THREAD

**Issue by aleksa000777** [aleksa000777/GameProject#2]
I've got problem when you click too fast it open more than 2 pictures
How to set delay then you open 2 pictures and have to wait till it's close(if they don't match)
i know that I should put smth like 
e.preventDefault();
or
$td.prop("disabled", true);
 and then 
$td.prop("disabled", false);
or set timeout
or e.stopPropagation();
or
use unbind and bind

i tried a lot but it doesn't work

**Comment by clay-reed-a** [comment]
Aleska, 

I just played your Memory Game and... this is amazing! 

I wouldn't've been able to even find this "more than 2 pictures open" bug had you not mentioned it. I am very impressed. :smile:  

There are a number of ways you could solve this problem. The way I solved it [when I made a Memory Game](http://memory.claytonalbachten.com) was:
- Do you have a way of keeping track of how many pictures are open? 
- Can you add a conditional to your `clickPicture` function that says:
  - If there are 2 open pictures, do not run anything.

If you can answer yes to both these questions, then you know what to do. :-) 

:waning_crescent_moon: :new_moon: :waxing_crescent_moon: :first_quarter_moon: :moon: :full_moon: :waning_gibbous_moon:  

Clay a
