### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [aleksa000777/GameProject#3]
Alexa,

Great job with your game. "Advanced" mode was surprisingly difficult. I like that you implemented variable difficulty levels. Also, really clever to use Image objects. Where did you go to learn about these? 

Your logic looks sound and you definitely exceeded the technical requirements of the game. Awesome stufff! Keep up the great work.

-Avi

**Comment by aleksa000777** [comment]
Thank you!
I google it.  :blush:
http://stackoverflow.com/questions/8810927/showing-an-image-from-an-array-of-images-javascript
and found this. It's give me the way to use attr src to set show() and compare to each other

**Comment by ajhofferber** [comment]
Hey Aleksa,

I really enjoyed playing your memory game! I thought that the ability to have 3 separate difficulty levels, as well as the ability to customize card backs were really great additional features and shows that you were able to have a really good handle on the logic of your game and how it was working.  Plus I was super excited about your "advanced" mode feature. :)

Overall, I think you did really well with the assignment! It was fun to look through how you ended up piecing it all together.

Score: 3 (refer to project markdown for scoring rubric)

-Ash
